### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Aaronduino** [Aaronduino/ttrai#1]
This is the todo list for the code:

**Highest Priority**
- [ ] Figure out a license for the code, then publish code on GitHub (figure out how to deal w/ the libraries)

**High Priority**
- [x] Add drawing from visible deck
- [x] Check if moves are legal
- [x] Check if data is corrupted when attributes about track purchases are set

**Medium Priority**
- [x] Fix possible bug when checking track color when buying tracks

**Low Priority**
- [ ] Add GUI
- [ ] Make UI easier to use
- [ ] Write comments to explain code
- [x] Come up with a better solution of how to send hand data to AI (fix caps)
